# ! DO NOT set latest here USE custom hash !
image: registry.gitlab.com/satoshilabs/trezor/trezor-suite/base:30432a76306b0b3ae5f0fa57d0bc9a63fb4d025f

cache:
    key: node-modules-cache
    paths:
        # modules
        - node_modules/
        - packages/blockchain-link/node_modules/
        - packages/components/node_modules/
        - packages/components-v2/node_modules/
        - packages/components-storybook/node_modules/
        - packages/components-storybook-v2/node_modules/
        - packages/connect-explorer/node_modules/
        - packages/rollout/node_modules/
        - packages/suite/node_modules/
        - packages/suite-web/node_modules/
        - packages/suite-desktop/node_modules/
        - packages/suite-native/node_modules/
        - packages/suite-storage/node_modules/
        - packages/translations-manager/node_modules/

        # libs
        - packages/components/lib
        - packages/components-v2/lib
        - packages/blockchain-link/lib
        - packages/rollout/lib
        - packages/suite-storage/lib
        - packages/translations-manager/lib

before_script:
    - yarn

install and build:
    stage: setup environment
    script:
        - yarn
        - yarn run build:libs

variables:
    PACKAGE_PATH_COMPONENTS: 'packages/components-storybook'
    PACKAGE_PATH_SUITE_WEB: 'packages/suite-web'
    PACKAGE_PATH_SUITE_NATIVE: 'packages/suite-native'
    PACKAGE_PATH_SUITE_DESKTOP: 'packages/suite-desktop'
    PACKAGE_PATH_CONNECT_EXPLORER: 'packages/connect-explorer'
    DEV_SERVER_URL: 'https://suite.corp.sldev.cz'

stages:
    - setup environment
    - lint and prettier
    - typescript type check
    - unit testing
    - build
    - deploy to dev servers
    - integration testing
    - build desktop apps
    - misc

include:
    - ci/environment.yml
    - ci/packages/components.yml
    - ci/packages/components-v2.yml
    - ci/packages/components-storybook.yml
    - ci/packages/components-storybook-v2.yml
    - ci/packages/suite.yml
    - ci/packages/suite-web.yml
    - ci/packages/suite-desktop.yml
    - ci/packages/suite-native.yml
    - ci/packages/blockchain-link.yml
    - ci/packages/rollout.yml
    # - ci/packages/connect-explorer.yml
